version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: romaniaendpoints_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: romaniaendpoints_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local 